version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: meatspace_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5433}:5432" # Maps port 5432 in container to 5433 (or DB_PORT) on host
    restart: unless-stopped

volumes:
  db-data:
    driver: local