services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - prefect_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
      PREFECT_API_DATABASE_TIMEOUT: 600
      PREFECT_API_URL: http://backend:4200/api
    ports:
      - "4200:4200"
    restart: unless-stopped
    command: >
      sh -c "
        echo '⏳ Waiting for Postgres…';
        until pg_isready -h postgres -p 5432 -U prefect -d prefect; do sleep 2; done;
        echo '✅ Postgres is up — launching Prefect';
        exec prefect server start --host 0.0.0.0
      "

volumes:
  prefect_pgdata: