providers = ["python", "node"]

[phases.install-python]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build-ui]
dependsOn = ["install-python"]
cmds = [
  "cd ui && npm ci",
  "npm run build",
  "mkdir -p backend/static && cp -r ui/dist/* backend/static/"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 8000"