# For PRODUCTION environment

envVarGroups:
  - name: app-secrets
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: AWS_ACCESS_KEY_ID
      - key: AWS_SECRET_ACCESS_KEY
      - key: AWS_REGION
      - key: S3_PROD_BUCKET_NAME
      - key: CLOUDFRONT_PROD_DOMAIN
        fromDatabase:
          name: app-db
          property: connectionString

# ---------------------------------------------------------------------------
#  DATABASES
# ---------------------------------------------------------------------------
databases:
  - name: app-db
    plan: basic-1gb # TODO: Upgrade to 'standard' for production workloads
    postgresMajorVersion: 16
    ipAllowList:
      - source: "50.1.246.139/32"
        description: "El Segundo House"

# ---------------------------------------------------------------------------
#  SERVICES
# ---------------------------------------------------------------------------
services:
  #  1) Phoenix Web Service (The "Job Enqueuer")
    # Handles web traffic and creates jobs (does NOT process the jobs)
  - name: phoenix-web
    type: web
    env: docker
    plan: starter # TODO: Scale based on web traffic
    rootDir: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: "production"
      - key: MIX_ENV
        value: "prod"
      - key: PHX_SERVER
        value: "true"
      - key: PHX_HOST
        fromService:
          type: web
          name: phoenix-web
          property: host
      - key: PORT
        value: "4000"
      - key: DATABASE_URL
        fromDatabase:
          name: app-db
          property: connectionString
      # For now, this will only run the 'default' queue for small,
      # quick jobs and the Cron scheduler (will NOT run ingest, embed, etc.)
      - key: OBAN_QUEUES
        value: "default"
      - fromGroup: app-secrets
    autoDeploy: true
    branch: main