envVarGroups:
  - name: app-secrets          # (already empty – will hold shared secrets later)
    envVars: []

# ---------------------------------------------------------------------------
#  DATABASES
# ---------------------------------------------------------------------------
databases:
  # Main Phoenix application DB
  - name: app-db
    plan: basic-1gb
    postgresMajorVersion: 16
    ipAllowList:
      - source: "50.1.246.139/32"
        description: "El Segundo House"

  # Prefect metadata DB
  - name: prefect-db
    plan: basic-1gb
    postgresMajorVersion: 16
    # ipAllowList: []  # optional – Prefect server connects internally

# ---------------------------------------------------------------------------
#  SERVICES
# ---------------------------------------------------------------------------
services:
  # -------------------------------------------------------------------------
  #  1) Phoenix LiveView Web
  # -------------------------------------------------------------------------
  - name: phoenix-web
    type: web
    env: docker
    plan: starter
    rootDir: frontend
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      # --- App / Phoenix ---
      - key: APP_ENV
        value: "production"
      - key: MIX_ENV
        value: "prod"
      - key: PHX_SERVER
        value: "true"
      - key: PHX_HOST
        value: phoenix-web-yupe.onrender.com
      - key: PORT
        value: "4000"

      # --- DB connection ---
      - key: DATABASE_URL
        fromDatabase:
          name: app-db
          property: connectionString
      - key: PROD_DATABASE_URL
        fromDatabase:
          name: app-db
          property: connectionString

      # --- Secrets / AWS ---
      - key: SECRET_KEY_BASE
        generateValue: true
      - fromGroup: app-secrets

    autoDeploy: true
    branch: main

  # -------------------------------------------------------------------------
  #  2) Prefect Server (API + UI)
  # -------------------------------------------------------------------------
  - name: prefect-server
    type: web
    env: docker
    plan: starter
    dockerfilePath: ./backend/Dockerfile.prefect-server

    # Render sets $PORT (default 10000).  We bind Prefect to it.
    startCommand: >
      bash -c "prefect server start --host 0.0.0.0 --port $PORT"

    healthCheckPath: /api/health

    envVars:
      # Prefect's metadata database
      - key: PREFECT_API_DATABASE_CONNECTION_URL
        fromDatabase:
          name: prefect-db
          property: connectionString

      # Shared secrets if Prefect ever needs them
      - fromGroup: app-secrets

    autoDeploy: true     # change to false if you prefer manual deploys
    branch: main