envVarGroups:
  - name: app-secrets
    envVars: []

databases:
  - name: app-db # Main application database
    plan: basic-1gb
    postgresMajorVersion: 16
    ipAllowList:
      - source: "50.1.246.139/32"
        description: "El Segundo House"

services:
  # --- Phoenix LiveView Web Service ---
  - name: phoenix-web
    type: web
    env: docker
    plan: starter
    rootDir: frontend
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      # --- Application Environment ---
      - key: APP_ENV
        value: "production"

      # --- Phoenix Specific ---
      - key: MIX_ENV
        value: "prod"
      - key: PHX_SERVER
        value: "true"
      - key: PHX_HOST
        value: phoenix-web-yupe.onrender.com
      - key: PORT
        value: "4000"

      # --- Database Connection (for Phoenix/Ecto) ---
      - key: DATABASE_URL
        fromDatabase:
          name: app-db
          property: connectionString
      - key: PROD_DATABASE_URL # runtime.exs might prioritize this
        fromDatabase:
          name: app-db
          property: connectionString

      # --- Secrets & AWS Configuration ---
      - key: SECRET_KEY_BASE
        generateValue: true   # Render will generate a secure value
      - fromGroup: app-secrets

    autoDeploy: true
    branch: main