envVarGroups:
  - name: app-secrets
    envVars: []

# ---------------------------------------------------------------------------
#  DATABASES
# ---------------------------------------------------------------------------
databases:
  - name: app-db
    plan: basic-1gb
    postgresMajorVersion: 16
    ipAllowList:
      - source: "50.1.246.139/32"
        description: "El Segundo House"

  - name: prefect-db
    plan: basic-1gb
    postgresMajorVersion: 16

# ---------------------------------------------------------------------------
#  SERVICES
# ---------------------------------------------------------------------------
services:
  # -------------------------------------------------------------------------
  #  1) Phoenix LiveView Web
  # -------------------------------------------------------------------------
  - name: phoenix-web
    type: web
    env: docker
    plan: starter
    rootDir: frontend
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: "production"
      - key: MIX_ENV
        value: "prod"
      - key: PHX_SERVER
        value: "true"
      - key: PHX_HOST
        value: phoenix-web-yupe.onrender.com
      - key: PORT
        value: "4000"

      - key: DATABASE_URL
        fromDatabase:
          name: app-db
          property: connectionString
      - key: PROD_DATABASE_URL
        fromDatabase:
          name: app-db
          property: connectionString

      - key: SECRET_KEY_BASE
        generateValue: true
      - fromGroup: app-secrets

    autoDeploy: true
    branch: main

  # -------------------------------------------------------------------------
  #  2) Prefect Server (API + UI)
  # -------------------------------------------------------------------------
  - name: prefect-server
    type: web
    env: docker
    plan: starter
    dockerfilePath: ./backend/Dockerfile.prefect-server

    healthCheckPath: /api/health

    envVars:
      - key: PORT                     # Render listens on this
        value: "4200"
      - key: PREFECT_SERVER_API_HOST  # Bind externally
        value: 0.0.0.0
      - key: PREFECT_API_DATABASE_CONNECTION_URL
        fromDatabase:
          name: prefect-db
          property: connectionString
      - fromGroup: app-secrets
